algoritmo "semnome"
// Função :
// Autor :
// Data : 25/03/2019
// Seção de Declarações 
var
C,M,D,Mi:real
inicio
// Seção de Comandos 
Escreva (" digite os centimetros")
leia(C)
M<-(C/100)
D<-(C/10)
Mi<-(C/1000)
Escreval("o valor dos centimetros em metros será =",M)
Escreval("o valor dos centimetros em decimetros será =",D)
Escreval("o valor dos centimetros em milimetros será =",Mi)
fimalgoritmo
