algoritmo "semnome"
// Função :
// Autor :
// Data : 25/03/2019
// Seção de Declarações 
var
A,B,C,D,X1,X2:real
inicio
// Seção de Comandos
Escreva ("O valor de A")
Leia(A)
Escreval(" O valor de B")
Leia(B)
Escreval ("o valor de C")
Leia (C)
D<-(B^2)-4*A*C
Escreval("delta é iagual a",D)
X1<-(-B+RaizQ(D))/2*A
escreval ("X1 é igual a" ,X1)
X1<-(-B-RaizQ(D))/2*A
escreval ("X2 é igual a" ,X2)

fimalgoritmo
